### ISSUE TITLE
Add more accurate percentile to Global Information

### ISSUE THREAD

**Issue by jaakkos** [mhjort/clj-gatling#18]
As Gil mentions in his talk http://www.infoq.com/presentations/latency-response-time
95th and 99th percentiles are not always enough.

**Comment by mhjort** [comment]
At the moment all the reports are produced using gatling-highcharts which doesn't do that automatically. 

However, I have been thinking that clj-gatling should produce it's own simple report that is shown in command line. Then gatling-highcharts would be used only for detailed graphical reports

**Comment by mhjort** [comment]
Added this to Future milestone because it makes sense to do this after https://github.com/mhjort/clj-gatling/issues/26 is solved.

**Comment by mhjort** [comment]
clj-gatling is now using latest Gatling Highchart reporter which has 4 different percentiles. So I think this is solved.
