### ISSUE TITLE
Allow for early termination and partial data collection

### ISSUE THREAD

**Issue by sarudak** [mhjort/clj-gatling#21]
Running long stress tests with clj-gatling is rather opaque, furthermore I have had tests run far far longer than I specified in the duration. I would like to have the option to terminate the process early and have some insight into how the process is going without having to wait until the end. Perhaps the call to run simulation could return immediately with a func that can be called to terminate the simulation and an atom that is periodically updated with partial information?

**Comment by mhjort** [comment]
If tests are running far longer than specified that's a definitely a bug. Do you have an example that is reproducible? I could take a look on that.

**Comment by mhjort** [comment]
Early termination is a good idea. However, I have to think about it a bit so that it fits to current internal design.

**Comment by sarudak** [comment]
I think there's actually two issues here. One is (I'm guessing) that regardless of duration already started scenarios will complete so if I try to do a 30 sec test and my scenario is 5 min it takes that long no matter what and at the end of a 20 minute test the stragglers will finish their scenarios. I'm guessing this is WAD.

The other is when I push the concurrent users over 100 to say 150 or 200 then I seem to get less traffic than at 100 users and the scenarios never seem to finish even if I wait an extra 30 min past time. Not sure what's going on there. Maybe my computer just can't handle it but it's not giving me a lot of visibility into what's happening.

**Comment by mhjort** [comment]
You're right. clj-gatling checks whether it should finish after running scenario. So it will finish up all the scenarios that have been started before. If you have small timeout value for scenario steps that's usually not a problem. Also that way ongoing requests are never interrupted (meaning that all responses are checked). For me that has been important thing but I understand that's not always needed. How long timeout you are using in your tests?

**Comment by sarudak** [comment]
I'm using standard clj-http timeouts. It's less the timeout than that I'm running 20+ steps in the scenario with a sleep-before of 1-10 sec each to simulate user delay. Cutting the delay for my testing helps a lot so I made that configurable.

**Comment by mhjort** [comment]
Implementing stop condition check after each scenario step is quite trivial. I added a separate issue about this #24 .

**Comment by mhjort** [comment]
Solved in https://github.com/mhjort/clj-gatling/issues/24
