### ISSUE TITLE
concurrency as users per second

### ISSUE THREAD

**Issue by ghost** [mhjort/clj-gatling#25]
Do you think it would be an idea to specify concurrency as users per second as Gatling does?

**Comment by mhjort** [comment]
I didn't know that Gatling has a such feature. But yeah it should not be that hard to implement. Definitely something to be added to clj-gatling.

So in options you could either use ```:concurrency``` or then ```:requests-per-second```

However, I am not sure when I have time to implement this. PRs are always welcome ;)

**Comment by jakubholynet** [comment]
I could implement this perhaps. @mhjort could you be so kind and point me where in code to look / start? Thank you!

**Comment by viesti** [comment]
Just dropping a friendly ping, I'd like this feature too :)

**Comment by viesti** [comment]
There's also this nice little library for throttling: https://github.com/brunoV/throttler. Might not be of direct use but the token bucket idea for [rate limiting](http://brunov.org/clojure/2014/05/14/throttler/) could be useful.

**Comment by jakubholynet** [comment]
Thank you! I run out of time but perhaps somebody else will take the ball :-) If not, then I will the next time I have an opportunity.
