### ISSUE TITLE
More accurate response time

### ISSUE THREAD

**Issue by visibletrap** [mhjort/clj-gatling#28]
Just throwing my notice/idea out. Please feel free to ignore it if it's not align with your clj-gatling direction.

It seems like clj-gatling reports response time by timing the whole time spent in each step function. I think this could be hugely misleading as the time may spent more in the test logistics rather than in the working of system under test which we care more about.

Some example of the thing I'm doing inside of step function:
* http client parses stuffs such as headers, cookie
* set cookie for the next step
* get cookie from the previous step
* parse body to get form token

Have you had any thought about this? I personally not sure how could we fix this situation. One idea is to provide 2 hooks for calling to start/stop the timer. Then trying to hook that with the thing that exercise system under test such as the http clients

Thanks

**Comment by mhjort** [comment]
You're right. I have to think this a bit. I wouldn't want to do it too hard for users to write tests. That's why I have avoided so far adding hook methods. However, I could add a mention about this problem to README so that does not happen as a suprise.

**Comment by visibletrap** [comment]
Yeah, I agree that hook methods will make things look way more complicated. I definitely see and understand how much you care about clj-gatling usability through the writing in README.

By the way, thank you for build and share this project. It's very useful even though I ignore time report and charts. We use it to push our system to its limit to find failure point. And also wrapping `clj-gatling.core/run` with a timer to measure overall processing time instead. Relatively compare the time spent in processing 100, 500, 1000, ... concurrent requests give us a lot more understanding of our system.
