### ISSUE TITLE
Option to provide custom measurements and errors to reporter

### ISSUE THREAD

**Issue by Cka3** [mhjort/clj-gatling#29]
Hello and thanks for this great lib 👍 

My problem with it is that it measures time which :request function took to return 'true' and in my case that is not exactly what I want to measure, because what my :request function does is:

```clojure
(defn api-call [{:keys [my-api-call-fn body] :as context}]
  (let [params (check-body-with-schema body)      ;checks some params before actual request
        {:keys [status actual-request-time body]} (my-api-call-fn params)]   ;constructs and sends actual request
     (if (and  (= status 200) 
               (convert-json-to-edn-and-check-it-with-clojure-specs body)) ; checks responce body
      true
      false))) ;  and only after that is will return
```

But what I want to measure is `actual-request-time` (or ideally request and response time) so it would be great if I would be able to supply those response times to gatling reporter by returning some map or a key by which it can then lookup those values in context map. 

Also same thing go with errors supplying those to reporter would be awesome. 

I hope I was clear and thanks for your response in advance.

**Comment by mhjort** [comment]
Great that you have found the library useful.

I get your point. There was an feature request related to this a while ago (see https://github.com/mhjort/clj-gatling/issues/28). The issue was closed because back then I couldn't figure out easy way to support this.

However, since latest version (0.8.1) clj-gatling supports specifying your own reporter maybe it would make sense to have a way to specify your own custom measurements too. I just have to think how to make this in a backwards compatibility manner. I'll give some thought on this and will get back to you soon.

**Comment by Cka3** [comment]
Thanks for answer!
Maybe our :request function can return map with 

```clojure
{ :start 1470329374764
  :end 1470329375153
  :result true} 
```
As I understand you already performing checks for returned values  boolean? or chan? so it will not break any existing code, just one more check.

I've tried to understand your source code, but I'm to new to programming to provide you  with any useful help for now.

**Comment by Cka3** [comment]
Any news on this one?

**Comment by mhjort** [comment]
Sorry about the delay. I have been thinking about this. I want to separate the custom values and clj-gatling required values. This way the change is more future-proof. So request function should return map with keys ```:result```, ```:context``` and ```:custom-results```. The last key would be optional and that would be passed to reporter.

I already made a small internal refactoring that makes it easier to implement this. Implementing this shouldn't be a big task. I'll try to implement this soon.

**Comment by mhjort** [comment]
I've been thinking this a lot. I decided not to include yet another way for returning values from request functions. Instead I made a change that makes the request context (after and before executing it) available in reporter. This is implemented as keys `:context-before` and `:context-after`. You should be able to implement the thing you wanted by inserting custom data to context.

See https://github.com/mhjort/clj-gatling/pull/34

**Comment by mhjort** [comment]
Released 0.8.3 with this support.

**Comment by Cka3** [comment]
thanks. Any info on how to actually use it? Can't figure it out from your commits.

**Comment by mhjort** [comment]
I'll add an example to repository tomorrow to make it more clear. Documentation is not that clear.

**Comment by mhjort** [comment]
@Cka3 Check https://github.com/mhjort/clj-gatling/blob/master/examples/clj_gatling_example/custom_reporter.clj

**Comment by Cka3** [comment]
Thanks. What about custom measures? Can I assoc my own :start and :end  to context now ?

**Comment by Cka3** [comment]
So we can't supply our own measurements to default reporter?

**Comment by mhjort** [comment]
Unfortunately not. I am not sure if this is even possible with current Gatling Highcharts reporter that is the default reporter. I created now issue about investigating what would be possible. See: https://github.com/mhjort/clj-gatling/issues/43
