### ISSUE TITLE
Improve performance by configuring thread pool size based on concurrency

### ISSUE THREAD

**Issue by mhjort** [mhjort/clj-gatling#38]
clj-gatling uses `core.async` version 0.2.374 which has a "fixed" size thread pool. The size is based on number of cores the machine have but there is no way for user to increase the size. For load tests that use high performance asynchronous non blocking IO (e.g. `http-kit`) library this is not an big issue. However libraries that require thread per get request (e.g. `clj-http`) this is a real limitation. 

Latest version of `core.async` supports setting the thread pool size using system property. With that the thread pool could be set to match the concurrency used in the simulation.

**Comment by MarcoNicolodi** [comment]
@mhjort At the company i work for, event though we are using the library with http-kit and it was limited by number of the cores. Setting the JVM flag increased concurrency dramatically. I think that this is something that could have more highlight in the readme.

**Comment by mhjort** [comment]
Good point. I add mention about this to the readme.

BTW, could you share some details about your setup and the concurrency before / after setting the JVM flag. My plan was to test with different setups and add some recommendations for the thread pool size but haven't have time for that yet.

**Comment by mhjort** [comment]
Updated readme: https://github.com/mhjort/clj-gatling/blob/master/README.md#tuning-parallelism

Closing this one.
