### ISSUE TITLE
Passing users list to core/run

### ISSUE THREAD

**Issue by piranha** [mhjort/clj-gatling#39]
`simulation/run` accepts `users` as an option, but `core/run` does not pass it. Is this just overlooked or maybe a design choice?

**Comment by mhjort** [comment]
Design choice. ```core/run``` is the public API for library and with that I try to keep backwards compatibility as much as possible. That is also the documented API. The more stuff in ```core``` the more work there is to maintain :)

However, if there is a valid use case for adding ```users``` as an option to API I am not against that idea. What are you trying to do?

**Comment by piranha** [comment]
Well, I'm writing a stress test to check how our 'add to basket' functionality works, and for that I need a lot of various users which do things at different times. 

I'm not exactly sure what's the best way to handle this, and main idea was to read user credentials from a csv file and passing it down.

Maybe there is a better way to choose them?

**Comment by mhjort** [comment]
clj-gatling has a concept of virtual users. So for example if you run with concurrency 100 then there will be 100 virtual users running scenarios in parallel. When a virtual user finishes the scenario he starts running it again. Virtual user id (zero based) is passed in context object to every request function call. With that you can implement your case in a following way:

First read credentials from csv file.
```
(def all-credentials (read-100-user-credentials-from-csv-file))
```

Then use them in request function like this
```
(def my-request-fn [{:keys [user-id]}]
  (let [user-credentials (nth credentials user-id)]
    (add-to-basket user-credentials)))
```

Would that work in your case?

**Comment by piranha** [comment]
I guess it would work! It's just I thought about having more users than concurrency so that it would switch between them chaotically. :-) It seems I have to start writing something and then see if I really need that.

Thanks!
