### ISSUE TITLE
A more involved tutorial

### ISSUE THREAD

**Issue by slipset** [mhjort/clj-gatling#4]
I'd really like to see a more involved example where the result from one request is used either as input for the next request or as a way to decide the next request.

Example:
I'd like to performance-test my web-shop application through the following scenario (assuming each step has a separate UR)L:
1) log in
    if login ok
        2) display list of products
        3) select a random product from that list and put it in my shopping basket
        4) checkout

And I want timing on all these endpoints.

Great talk yesterday :)

**Comment by mhjort** [comment]
Better later than never. I started a series of blog posts for giving better examples. First one is out: https://medium.com/@mhjort/performance-testing-in-clojure-part-i-d75790b056e7

The first post doesn't fully cover you case but I try to get back to than in next post. (In near future that is)

**Comment by mhjort** [comment]
I'll rewrote the readme to be more elaborative a while ago. Closing this for now.
