### ISSUE TITLE
Add instance-id per running instance of each scenario

### ISSUE THREAD

**Issue by mehretaban** [mhjort/clj-gatling#44]
Since user-id is limited to the number of concurrent users, having an instance-id per running instance of each scenario could be helpful for picking next test data item from input data sets. It could be used in data feeders implementations. instance-id of running instances of different scenarios, all can start from zero. 
Following table shows context value for two scenarios A and B with concurrency 3:

context for running instance of scenario A | context for running instance of scenario B
-|-
instance-id: 0, user-id: 0 |instance-id: 0, user-id: 1
instance-id: 1, user-id: 2|instance-id: 1, user-id: 0
instance-id: 2, user-id: 1|instance-id: 2, user-id: 2
instance-id: 3, user-id: 0|instance-id: 3, user-id: 1
...|...

Furthermore,  if we could set instance-id-strategy in simulation for specifying how to generate instance-id can be an extra helpful feature. In the other words, to determine to create instance-ids sequentially regardless of they belong to which scenario or to be unique per scenario. 

Following table shows context value for two scenarios A and B with concurrency 3:

context for running instance of scenario A | context for running instance of scenario B
-|-
instance-id: 0, user-id: 0 |instance-id: 1, user-id: 1
instance-id: 2, user-id: 2|instance-id: 3, user-id: 0
instance-id: 4, user-id: 1|instance-id: 5, user-id: 2
instance-id: 6, user-id: 0|instance-id: 7, user-id: 1
...|...

**Comment by mhjort** [comment]
I think I understand what you are looking for and it makes sense. Unfortunately the current design in ```simulation``` namespace runs different scenarios independently of each other. So this not trivial to implement at the moment.

I need to think this a bit. I most probably won't have time to look this into more detail in this week. But I will try to arrange some time after that. In a meanwhile if you can provide PR which implements this that would be awesome.

**Comment by vovata** [comment]
Could it be possible to add pre-hook function on scenario level? Then the implementation of instance-id will be done there if it is necessary.

**Comment by mhjort** [comment]
That is a good idea. Added a separate issue https://github.com/mhjort/clj-gatling/issues/54

**Comment by mhjort** [comment]
Release `0.11.0` contains support for scenario pre & post hook functions. Using those you should be able to create a setup that you described.
