### ISSUE TITLE
Feeding and templating

### ISSUE THREAD

**Issue by etherny** [mhjort/clj-gatling#46]
Hello, any feature for custom feeding ?
Did this library support any templating like mustashe based on feeding data ?

**Comment by mhjort** [comment]
There is no ready-made support for custom feeding. However, my goal has been that this library should support building your own pretty easily. 

The context that is passed to your request function contains `user-id` which is a unique id for all "virtual users". You can have a Mustache template where you pass that `user-id`. Would that work in your case?

There is also a feature request for instance id. See https://github.com/mhjort/clj-gatling/issues/44. However, I don't know when I have time to implement that.

**Comment by mhjort** [comment]
Custom feeding can be implemented by using existing features (scenario pre-hooksa and `user-id`).
