### ISSUE TITLE
Skip adding :user-id on each step

### ISSUE THREAD

**Issue by vovata** [mhjort/clj-gatling#52]
I think it is better to add :user-id once in the function run-scenario-once before going in the go-loop instead of trying to do it in the function async-function-with-timeout -->> original-context-with-user (assoc original-context :user-id user-id) on each step of the scenatio.

**Comment by mhjort** [comment]
I chose this approach to be sure that `:user-id` is really given to each step. This way user cannot override ever. I know that this makes code a bit more uglier. Other than that do you see there is a potential problem with current approach?

**Comment by vovata** [comment]
Ok. I understand. Sounds reasnable.
