### ISSUE TITLE
Simulation with concurrency distribution fails when duration left unspecified

### ISSUE THREAD

**Issue by tkriik** [mhjort/clj-gatling#56]
The progress value given to concurrency distribution callback stalls at 0.0 if `:requests` is specified in options instead of `concurrency`. I suggest disabling the feature in such a case.

**Comment by mhjort** [comment]
Sorry, are you talking about duration or concurrency? In the title you mention leaving `duration` unspecified but in the comment you talk about `concurrency`.

I have tested this with both `:requests` and `:duration`. I can't find the issue. Could you post me an example where it is failing.

**Comment by tkriik** [comment]
Ah, sorry, typo there! I mean I had the following options, if I remember correctly:

```
:requests X
:concurrency Y
:concurrency-distribution (fn [progress ctx] ...) ; here progress is always 0.0
```

I can give more details when I return to work.

**Comment by mhjort** [comment]
I couldn't reproduce this. Closing for now
