### ISSUE TITLE
Upgrade http-kit for JDK 9

### ISSUE THREAD

**Issue by tirkarthi** [mhjort/clj-gatling#57]
It seems that the project uses a version of http-kit that is incompatible with JDK 9 and above. It is fixed upstream and upgrading it will help in JDK 9 compatibility.

Relevant http-kit upstream issue : https://github.com/http-kit/http-kit/issues/356
Relevant release : https://github.com/http-kit/http-kit/releases/tag/2.3.0-beta2
Latest RC release : https://github.com/http-kit/http-kit/releases/tag/v2.3.0-RC1

**Comment by mhjort** [comment]
Thanks for pointing this out. I am planning to make a new major release of clj-gatling within a week or so. I will upgrade to latest httpkit version before doing that.

**Comment by lamuria** [comment]
hey @mhjort any update on this one?

**Comment by mhjort** [comment]
Hi! I just released a new version `0.12.0` that has latest stable release of http-kit. This version should be now JDK 9 compatible.

**Comment by lamuria** [comment]
Thanks @mhjort! it's working now! I guess we can close this one

**Comment by tirkarthi** [comment]
Closing this since it's fixed with version 0.12.0

Thanks
