### ISSUE TITLE
Issues with high concurrency

### ISSUE THREAD

**Issue by t-augusto** [mhjort/clj-gatling#61]
I'm currently performing tests setting the concurrency to about 10k. 
However I'm getting inconsistent results, please correct me if I'm understanding something wrong.

I currently only have one scenario with 6 steps. My intention is to perform 60k requests in that sequential manner as defined in the steps, since each request depends on the result of the one before. However the requests don't seem to be evenly distributed, which I don't quite get why, on one test the first step had been done 8.5k times and on another test the first step had been done 35k times, more than half of the total of requests.
Is there something I'm missing as to why is the test behaving this way? The only argument I'm setting is the concurrency, nothing else, other than passing context between steps.

**Comment by mhjort** [comment]
Sounds weird. Could you share your scenario? No need for details. I can take a look if I can see your scenario structure

**Comment by mhjort** [comment]
Haven't been able to reproduce this. Closing the issue.
