### ISSUE TITLE
clj-time

### ISSUE THREAD

**Issue by AndreaCrotti** [mhjort/clj-gatling#65]
I noticed that this project requires and uses clj-time, which is deprecated in favour of the java API from version 8 onwards. 
https://github.com/clj-time/clj-time

It would be great to just require the java API object at least in the scenario configuration (for the duration) instead of a joda-time object.

**Comment by mhjort** [comment]
Agreed. In all the places where duration is required clj-gatling should use
Java 8 date objects by default. I also like to keep backwards
compatibility. So clj-time should be kept as option.

This is definitely a thing that should be fixed. I can take a look when I
have time. Pull requests are also always welcome!

**Comment by AndreaCrotti** [comment]
If you leave clj-time as an option then doesn't it mean still requiring the dependency anyway?
I think it should be fine if newer versions only take java 8+ date/time objects, keeping clj-time around would maybe defeat the purpose a bit imho.

**Comment by mhjort** [comment]
You are right. This could be implemented in a way that both Java 8 dates
and clj-time are accepted and by default next version of clj-gatling does
not have clj-time as a dependency. This way old users don't have to change
their code. Only thing they have to do is to add explicit clj-time
dependency

**Comment by mhjort** [comment]
This turned out to be trickier than I thought. I now have a PR ready that I am going to merge soon. https://github.com/mhjort/clj-gatling/pull/69

**Comment by mhjort** [comment]
clj-gatling `0.16.0` uses Java 8 time api by default and not include `clj-time` anymore. Closing this one.

**Comment by AndreaCrotti** [comment]
Nice thanks!
