### ISSUE TITLE
Steps running serially?

### ISSUE THREAD

**Issue by AndreaCrotti** [mhjort/clj-gatling#67]
From what I understood from the docs, steps in a given scenario will run serially, so one after the other.
I'm seeing that if add an extra step the requests/sec more or less halves, which would suggest that they are actually being run in parallel and I'm maxing out on the local concurrency.

In case it helps I'm using clj-http and I tweaked the clojure.core.async-pool-size, my other attempts (using core.async and the `async true` option) failed, but just tweak at least seems to do the job.

**Comment by mhjort** [comment]
Sounds odd. Scenarios are run in paralled and steps are run serially. Could you show an example how does your scenario look like? I could take a look.

**Comment by AndreaCrotti** [comment]
Yeah maybe it's something wrong I was doing, I'm creating a sample project soon for a blog post, so hopefully I can find out more while I do that.

**Comment by mhjort** [comment]
I have not been able to reproduce this one. Closing this one for now. I can reopen if there is new data about this bug.
