### ISSUE TITLE
How to identify concurrency issues

### ISSUE THREAD

**Issue by AndreaCrotti** [mhjort/clj-gatling#68]
Kind of related to:
https://github.com/mhjort/clj-gatling/issues/67
I was wondering if you have hints about how to detect when the results (like reqs/sec) you get are actually the maximum your server can deal with, or the bottleneck is just the way you run the test.

I guess it's not easy to do find out, for example using clj-http until I saw the `clojure.core.async.pool-size` mention I was getting wrong results, but since I didn't actually know what was the maximum my server was capable of, I didn't know.

Maybe clj-gatling could somehow detect if you're doing something silly and alert you?

**Comment by AndreaCrotti** [comment]
I think that at least by parsing the results you should be able to see what was the actual concurrency and then check if that diverges too much from the desired concurrency set in the configuration.
I tried a few things but could not find a formula that makes sense, but in theory that should help right?

**Comment by mhjort** [comment]
I agree with you that clj-gatling should provide some tools to analyze if
there are client issues on concurrency. That's not trivial though. Have to
think about it

**Comment by AndreaCrotti** [comment]
One thing that might be useful for example is to log how many requests per sec are being done while the tests are running, and how many requests are in progress for example.

This way at least you could easily see if the problem is that the server responds slowly and lots of requests are just piling up or simply the concurrency is not set up correctly.

**Comment by mhjort** [comment]
That's definitely a good idea. Now clj-gatling is totally silent during the
test run. This could be implemented in a configurable way. By default
clj-gatling can write these metrics to stdout while running and behavior
can be overriden by user defined function that is called periodically with
the latest analytics.

Unfortunately this might require some changes to simulation runner. I am
currently on vacation and might not have time to implement this feature
just now. However, I think this is an important feature and will take a
look on this near future. PR is also always welcome.

**Comment by mhjort** [comment]
clj-gatling `0.16.0` added `:progress-tracker` for tracking progress (progress percent, sent requests, concurrency) that could be used for identifying concurrency issues. Could you try your simulation with this new version?

**Comment by AndreaCrotti** [comment]
ok great thanks I'll give it a go

**Comment by AndreaCrotti** [comment]
The progress tracker looks good thanks!
