### ISSUE TITLE
Kill a simulation?

### ISSUE THREAD

**Issue by AndreaCrotti** [mhjort/clj-gatling#72]
If I run a long (and possibly buggy) simulation from the repl, I can't really kill it without restarting the repl entirely.

I think ideally sending a cider-interrupt or equivalent should kill the whole thing, which I guess doesn't work out of the box because it's using heavily core.async under the hood right?

**Comment by mhjort** [comment]
You are right. There are few go loops that keep running if you interrupt the function call in repl. This is discussed more here: https://stackoverflow.com/questions/20485188/gracefully-exit-a-clojure-core-async-go-loop-on-kill

I have used the exit channel mechanism (a.k.a. poison pill) in other projects using core.async. This kind of feature could be added to clj-gatling too. For example there could be a function `kill-all-running-simulations` which would send message to all exit channels.

**Comment by mhjort** [comment]
Implemented in `0.17.3`
