### ISSUE TITLE
Add raw reporter

### ISSUE THREAD

**Issue by AndreaCrotti** [mhjort/clj-gatling#73]
It would be nice if clj-gatling had the ability to return the raw data as EDN.

One hack to get do that could be to parse the stats.js, which contains the data you want in a format like:

```javascript
stats: {
    "name": "Global Information",
    "numberOfRequests": {
        "total": "10000",
        "ok": "10000",
        "ko": "0"
    },
    "minResponseTime": {
...
```

which works but it's a massive hack.
This reporter could be also a separate library at first and integrate in clj-gatling if potentially useful to everyone.

**Comment by mhjort** [comment]
@AndreaCrotti There is now https://github.com/mhjort/clj-gatling/blob/master/src/clj_gatling/reporters/raw_reporter.clj Does that solve the issue?

**Comment by AndreaCrotti** [comment]
I haven't been able to test it yet because we have not touched load tests for a while, but it looks good anyway.
I should do some more work on this soon so I can finally try it out and I can give more feedback, thanks a lot!
